spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=spring_security_jwt_version_one;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
