spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=assign_java_five;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    database: sql_server
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
